//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public ADMINISTRADOR()
        {
            this.HORARIO_GIMNASIO = new HashSet<HORARIO_GIMNASIO>();
        }
    
        public int INT_ID_ADMINISTRADOR { get; set; }
        public string STR_CEDULA { get; set; }
        public Nullable<int> INT_CANTIDAD_HORAS_SEMANALES { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<HORARIO_GIMNASIO> HORARIO_GIMNASIO { get; set; }
    }
}
