//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.MEDIDA_POR_CLIENTE = new HashSet<MEDIDA_POR_CLIENTE>();
            this.MEMBRESIA_POR_CLIENTE = new HashSet<MEMBRESIA_POR_CLIENTE>();
            this.RUTINA = new HashSet<RUTINA>();
            this.VISITA = new HashSet<VISITA>();
        }
    
        public int INT_NUMERO_CLIENTE { get; set; }
        public string STR_CEDULA { get; set; }
        public Nullable<System.DateTime> DT_FECHA_INGRESO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<MEDIDA_POR_CLIENTE> MEDIDA_POR_CLIENTE { get; set; }
        public virtual ICollection<MEMBRESIA_POR_CLIENTE> MEMBRESIA_POR_CLIENTE { get; set; }
        public virtual ICollection<RUTINA> RUTINA { get; set; }
        public virtual ICollection<VISITA> VISITA { get; set; }
    }
}
