//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO_GIMNASIO
    {
        public int ID_HORARIO { get; set; }
        public Nullable<int> INT_ID_ADMINISTRADOR { get; set; }
        public string DIA { get; set; }
        public string ACTIVIDAD { get; set; }
        public Nullable<double> FT_HORA { get; set; }
        public string HORA { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
    }
}
