//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUCTOR
    {
        public INSTRUCTOR()
        {
            this.INSTRUCTOR_RUTINA = new HashSet<INSTRUCTOR_RUTINA>();
        }
    
        public int INT_ID_INSTRUCTOR { get; set; }
        public string STR_CEDULA { get; set; }
        public Nullable<int> INT_CANTIDAD_HORAS_SEMANALES { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<INSTRUCTOR_RUTINA> INSTRUCTOR_RUTINA { get; set; }
    }
}
