//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUCTOR_RUTINA
    {
        public int INT_ID_RUTINA { get; set; }
        public int INT_ID_INSTRUCTOR { get; set; }
        public Nullable<System.DateTime> Dt_Fecha_Mod { get; set; }
    
        public virtual INSTRUCTOR INSTRUCTOR { get; set; }
        public virtual RUTINA RUTINA { get; set; }
    }
}
