//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEBRESIA
    {
        public MEBRESIA()
        {
            this.MEMBRESIA_POR_CLIENTE = new HashSet<MEMBRESIA_POR_CLIENTE>();
        }
    
        public int INT_IDMEMBRESIA { get; set; }
        public string STR_NOMBRE_MEMBRESIA { get; set; }
        public Nullable<double> DB_PRECIO { get; set; }
        public Nullable<int> INT_PERIODO { get; set; }
    
        public virtual ICollection<MEMBRESIA_POR_CLIENTE> MEMBRESIA_POR_CLIENTE { get; set; }
    }
}
