//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDA
    {
        public MEDIDA()
        {
            this.MEDIDA_POR_CLIENTE = new HashSet<MEDIDA_POR_CLIENTE>();
        }
    
        public int INT_ID_MEDIDA { get; set; }
        public Nullable<System.DateTime> DT_FECHA_MEDIDA { get; set; }
        public Nullable<double> DB_ALTURA { get; set; }
        public Nullable<double> DB_IMC { get; set; }
        public Nullable<double> DB_BICDER { get; set; }
        public Nullable<double> DB_BICIZQ { get; set; }
        public Nullable<double> DB_CINTURA { get; set; }
        public Nullable<double> INT_EDAD { get; set; }
        public Nullable<double> DB_ESPALDA { get; set; }
        public Nullable<double> DB_MUSLO_DER { get; set; }
        public Nullable<double> DB_MUSLO_IZQ { get; set; }
        public Nullable<double> DB_PECHO { get; set; }
        public Nullable<double> DB_PESO { get; set; }
        public Nullable<double> DB_PORCENTAJE_GRASA { get; set; }
        public Nullable<double> DB_CADERA { get; set; }
    
        public virtual ICollection<MEDIDA_POR_CLIENTE> MEDIDA_POR_CLIENTE { get; set; }
    }
}
