//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDA_POR_CLIENTE
    {
        public int INT_NUMERO_CLIENTE { get; set; }
        public int INT_ID_MEDIDA { get; set; }
        public Nullable<System.DateTime> DT_FECHA_MEDIDA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
    }
}
