//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBRESIA_POR_CLIENTE
    {
        public int INT_NUMERO_CLIENTE { get; set; }
        public int INT_IDMEMBRESIA { get; set; }
        public Nullable<double> DB_PRECIO { get; set; }
        public Nullable<double> DB_MONTO_PENDIENTE { get; set; }
        public Nullable<int> INT_NUM_RECIBO { get; set; }
        public Nullable<System.DateTime> INT_FECHA_PAGO { get; set; }
        public string STR_OBSERVACIONES { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MEBRESIA MEBRESIA { get; set; }
    }
}
