//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.ADMINISTRADOR = new HashSet<ADMINISTRADOR>();
            this.CLIENTE = new HashSet<CLIENTE>();
            this.INSTRUCTOR = new HashSet<INSTRUCTOR>();
            this.users = new HashSet<users>();
        }
    
        public string STR_CEDULA { get; set; }
        public string STR_APELLIDO1 { get; set; }
        public string STR_APELLIDO2 { get; set; }
        public Nullable<System.DateTime> DT_FECHA_NACIMIENTO { get; set; }
        public string STR_PROFESION { get; set; }
        public byte[] IMG_FOTO { get; set; }
        public Nullable<double> FT_TAMANO_FOTO { get; set; }
        public string STR_TELEFONO1 { get; set; }
        public string STR_TELEFONO2 { get; set; }
        public string STR_DIRECCION { get; set; }
        public string STR_EMAIL { get; set; }
        public string STR_NOMBRE { get; set; }
        public Nullable<int> rol { get; set; }
    
        public virtual ICollection<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<INSTRUCTOR> INSTRUCTOR { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
