//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTINA
    {
        public RUTINA()
        {
            this.EJERCICIO_POR_RUTINA = new HashSet<EJERCICIO_POR_RUTINA>();
            this.INSTRUCTOR_RUTINA = new HashSet<INSTRUCTOR_RUTINA>();
        }
    
        public int INT_ID_RUTINA { get; set; }
        public Nullable<int> INT_NUMERO_CLIENTE { get; set; }
        public string STR_NOMBRE_RUTINA { get; set; }
        public Nullable<double> INT_DURACION_TOTAL { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<EJERCICIO_POR_RUTINA> EJERCICIO_POR_RUTINA { get; set; }
        public virtual ICollection<INSTRUCTOR_RUTINA> INSTRUCTOR_RUTINA { get; set; }
    }
}
