//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.userclaims = new HashSet<userclaims>();
            this.userlogins = new HashSet<userlogins>();
            this.userroles = new HashSet<userroles>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string STR_CEDULA { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<userclaims> userclaims { get; set; }
        public virtual ICollection<userlogins> userlogins { get; set; }
        public virtual ICollection<userroles> userroles { get; set; }
    }
}
